const FIELD_WIDTH = 20;
const FIELD_HEIGHT = 40;
const FIELD_BLOCK_SIZE = 20; // 10px

const PROBABILITY_LEFT = 0.25;
const PROBABILITY_RIGHT = 0.25;
const PROBABILITY_CENTER = 1 - PROBABILITY_LEFT - PROBABILITY_RIGHT;

const PROBABILITY_MEDKIT = 1 / (0.5 * FIELD_HEIGHT);
const HEALTH_RESTORE_MEDKIT = 10;

const PROBABILITY_SPIKES = 1 / (0.5 * FIELD_HEIGHT);
const HEALTH_DAMAGE_SPIKES = 10;


export default { FIELD_WIDTH, FIELD_HEIGHT, FIELD_BLOCK_SIZE, PROBABILITY_LEFT, PROBABILITY_RIGHT, PROBABILITY_CENTER, PROBABILITY_MEDKIT , HEALTH_RESTORE_MEDKIT, PROBABILITY_SPIKES, HEALTH_DAMAGE_SPIKES};